<?
$loginUrl = "/forum/ucp.php?mode=login";
$logoutUrl = append_sid("/forum/ucp.php", 'mode=logout', true, $this->userData->session_id);
 //"/forum/ucp.php?mode=logout";
?>
<br />
<?if(Zend_Auth::getInstance()->hasIdentity()){?>
<span style="padding:15px"><?=$this->userData->username_clean?></span>
<br />
<a class="button" href="<?=$logoutUrl?>"><span>Вийти</span></a>
<?}else{?>
<a class="button" href="<?=$loginUrl?>"><span>Увійти на сайт</span></a>
<br />
<?}?>
