
<?= $this->doctype() ?> <!-- This Line will output the doctype we set inside the bootstrap file -->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>  
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
  <title><?= $this->escape($this->title)?></title>
  <base href="http://pi/"/>
    <?=$this->headLink()
        ->appendStylesheet('css/global.css')
        ->appendStylesheet('js/dojo/dojo/resources/dojo.css')
        ->appendStylesheet('js/dojo/dijit/themes/soria/soria.css')
        ->appendStylesheet('js/dojo/dijit/themes/soria/soria_rtl.css')
        ->appendStylesheet('js/dojo/dojox/editor/plugins/resources/editorPlugins.css')
?>
  <?=$this->headScript()->appendFile('/js/jquery-1.3.2.js')?>
  <?=$this->dojo()->setLocalPath("/js/dojo/dojo/dojo.js")?>
</head> 
<body topmargin="0" bgcolor="#488EC2">
<table cellpadding="0" cellspacing="0" align="center" width="960" height="30" border="0">
	<tr height="100">
		<td width="17" background="images/left.gif"><p class="sp">&nbsp;</p></td>
		<td width="915" background="images/grad.gif" align="left" valign="middle">
		<img src="images/gerb.jpg" style=" float:left;margin-left:20px;"><p class="joke">

			<?= $this->title ? $this->title : "Нема заголовка"?>


			</p>
		</td>
		<td width="17" background="images/right.gif"><p class="sp">&nbsp;</p></td>
	</tr>
	<tr height="25">
		<td width="17" background="images/left.gif"><p class="sp">&nbsp;</p></td>
        <td width="915" bgcolor="#D7E5FA" style="padding:5px;"><?=$this->navigation()->breadcrumbs()?></td>
		<td width="17" background="images/right.gif"><p class="sp">&nbsp;</p></td>
	</tr>
	<tr height="25">
		<td width="17" background="images/left.gif"><p class="sp">&nbsp;</p></td>
		<td width="915" bgcolor="#FFFFFF" align="center" valign="top">
			<table cellpadding="0" cellspacing="0" align="center" width="915" height="10" border="0">
				<tr height="10"> 
					<td width="15"><p class="sp">&nbsp;</p></td>
					<td width="181"><p class="sp">&nbsp;</p></td>
					<td width="15"><p class="sp">&nbsp;</p></td>
					<td width="700"><p class="sp">&nbsp;</p></td>
					<td width="15"><p class="sp">&nbsp;</p></td>
				</tr>
				<tr height="10"> 
					<td width="15"><p class="sp">&nbsp;</p></td>
					<td width="181" align="center" valign="top">
						<!--begin menu table-->
						<table cellpadding="0" cellspacing="0" width="181" height="10" align="center">
							<tr height="34">
								<td width="181" height="34" align="center"><img src="images/menu_1.gif" width="181" height="34"></td>
							</tr>
<tr>
								<td width="181" height="10" background="images/menu_2.gif">
                                <a class="top" href="<?=$this->url(array('controller' => 'index', 'action' => 'index'), null, true)?>">Головна</a><br/>
                                <a class="top" href="<?=$this->url(array('controller' => 'forum', 'action' => 'index'), null, true)?>">Форум</a><br/>
                                <a class="top" href="<?=$this->url(array('controller' => 'gallery', 'action' => 'index'), null, true)?>">Галерея</a><br/>
                                <a class="top" href="<?=$this->url(array('controller' => 'articles', 'action' => 'index'), null, true)?>">Статті</a><br/>

                                <?=$this->render('authBlock.phtml')?>
									<?/*<a href="index.htm" class="top">Головна</a><br>
									<a href="news.htm" class="top">Новини</a><br>
									<a href="foods.htm" class="top">Каталог товарів</a><br>
									<a href="map.htm" class="top">Карта сайту</a><br>*/?>
								</td>
							</tr>
							<tr height="34">
								<td width="181" height="34" align="center"><img src="images/menu_3.gif" width="181" height="34"></td>
							</tr>
						</table>
						<!--end memu table-->
					</td>
					<td width="15"><p class="sp">&nbsp;</p></td>
					<td width="700" align="left" valign="top">
<?if($this->errors){foreach($this->errors as $error){?>
 <div class="error"><?=$error?></div>
<?}}?>
<?if($this->messages){foreach($this->messages as $message){?>
 <div class="message"><?=$message?></div>
<?}}?>
<hr color="#FFAB56;" width="685" size="2">
<div class="soria">
<?= $this->layout()->content?>
</div>
					</td>
					<td width="15"><p class="sp">&nbsp;</p></td>
				</tr>
				<tr height="10"> 
					<td width="15"><p class="sp">&nbsp;</p></td>
					<td width="181"><p class="sp">&nbsp;</p></td>
					<td width="15"><p class="sp">&nbsp;</p></td>
					<td width="700"><p class="sp">&nbsp;</p></td>
					<td width="15"><p class="sp">&nbsp;</p></td>
				</tr>
			</table>
		</td>
		<td width="17" background="images/right.gif"><p class="sp">&nbsp;</p></td>
	</tr>
	<tr height="25">
		<td width="17" background="images/left.gif"><p class="sp">&nbsp;</p></td>
		<td width="915"  bgcolor="#D7E5FA"><p class="authors"><!--place for author notes--></p></td>
		<td width="17" background="images/right.gif"><p class="sp">&nbsp;</p></td>
	</tr>
</table>






</BODY>
</html>

