<?if(IS_ADMIN){?><a href="<?=$this->url(array('controller' => 'articles', 'action' => 'add'))?>">Додати статтю</a><?}?>
<div class="clear"></div>
<?if($this->data->count()){?>
<?=($this->data)?>
<div class="clear"></div>
 <?foreach($this->data as $item){?>
<div style="padding:10px 0;">
<?if(IS_ADMIN){?>
<div>
  <a class="icon edit" href="<?=$this->url(array('controller' => 'articles', 'action' => 'edit', 'id' => $item->id))?>">Редагувати</a> | 
  <a class="icon delete" href="<?=$this->url(array('controller' => 'articles', 'action' => 'delete', 'id' => $item->id))?>">Видалити</a>
</div>
<?}?>
  <h2><a href="<?=$this->url(array('controller' => 'articles', 'action' => 'view', 'id' => $item->id))?>"><?=$item->getTitle()?></a></h2>
  <div class="clear"></div>
    <div class="fl" style="width:450px"><?=$item->getDescription()?></div>
  <div class="clear"></div>
</div>
    <?//$item->description?>
 <?}?>
<?}else{?>
 Немає статей
<?}?>
<div class="clear"></div>
<?=($this->data)?>
