<?if(IS_ADMIN){?><a href="<?=$this->url(array('controller' => 'gallery', 'action' => 'add'), null, true)?>">Додати картинку</a><?}?>
<?if($this->data->count()){?>
<div class="clear"></div>
<?=($this->data)?>
<div class="clear"></div>
 <?foreach($this->data as $item){?>
<div style="padding:10px 0;">
<?if(IS_ADMIN){?>
<div>
  <a class="icon edit" href="<?=$this->url(array('controller' => 'gallery', 'action' => 'edit', 'id' => $item->id))?>">Редагувати</a> | 
  <a class="icon delete" href="<?=$this->url(array('controller' => 'gallery', 'action' => 'delete', 'id' => $item->id))?>">Видалити</a></div><?}?>
  <div class="clear"></div>
  <div class="fl">
  <a href="<?=$this->url(array('controller' => 'gallery', 'action' => 'view', 'id' => $item->id))?>"><img width="150" src="<?=$item->getImageThumbnailUrl()?>"/></a>
  </div>
    <div class="fl" style="width:450px"><?=$item->getDescription()?></div>
  <div class="clear"></div>
</div>
    <?//$item->description?>
 <?}?>
<?}else{?>
 Немає картинок
<?}?>
<div class="clear"></div>
<?=($this->data)?>
