<?
$prev = $this->item->prevItem();
$next = $this->item->nextItem();
?>
<table border="0" width="100%" height="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td width="30%">
        <?if($prev){?>
        <a href="<?=$this->url(array('controller' => 'gallery', 'action' => 'view', 'id' => $prev->id), null, true)?>">попереднє фото</a>
        <?}?>
    </td>
    <td width="40%" align="center">
        <a href="<?=$this->url(array('controller' => 'gallery', 'action' => 'index'), null, true)?>">До списку</a>
    </td>
    <td width="30%" align="right">
        <?if($next){?>
        <a href="<?=$this->url(array('controller' => 'gallery', 'action' => 'view', 'id' => $next->id), null, true)?>">наступне фото</a>
        <?}?>
    </td>
  </tr>
</table>
